version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
  node:
    build: .
    restart: always
    image: node:latest
    ports:
      - "8080:80"
    depends_on:
      biiig-image-db:
                condition: service_started
                restart: true
    environment:
      - DB_URI=mongodb://mongo:27017
    volumes: 
      - ./data/archive:/app/archive